services:
  - type: web
    name: flask-selenium-app
    env: python
    buildCommand: |
      apt-get update && apt-get install -y wget unzip curl gnupg
      # Install Google Chrome
      wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
      apt install -y ./google-chrome-stable_current_amd64.deb
      # Get the installed Chrome version
      CHROME_VERSION=$(google-chrome --version | grep -oP '\d+\.\d+\.\d+\.\d+' | head -n1)
      CHROME_MAJOR_VERSION=$(echo $CHROME_VERSION | cut -d '.' -f 1)
      # Install matching ChromeDriver
      wget -N https://chromedriver.storage.googleapis.com/${CHROME_VERSION}/chromedriver_linux64.zip || wget -N https://chromedriver.storage.googleapis.com/${CHROME_MAJOR_VERSION}.0.0/chromedriver_linux64.zip
      unzip chromedriver_linux64.zip
      mv chromedriver /usr/bin/chromedriver
      chmod +x /usr/bin/chromedriver
      # Verify Chrome and ChromeDriver installation
      which google-chrome
      google-chrome --version
      which chromedriver
      chromedriver --version
      # Install Python dependencies
      pip install -r requirements.txt
    startCommand: gunicorn app:app --bind 0.0.0.0:5000
