services:
  - type: web
    name: flask-selenium-app
    env: python
    buildCommand: |
      apt-get update && apt-get install -y wget unzip curl gnupg
      # Install Google Chrome
      wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
      apt install -y ./google-chrome-stable_current_amd64.deb
      # Verify Chrome installation
      which google-chrome
      google-chrome --version
      # Install Python dependencies
      pip install -r requirements.txt
    startCommand: gunicorn app:app --bind 0.0.0.0:5000
    envVars:
      - key: GOOGLE_CHROME_BIN
        value: /usr/bin/google-chrome

